// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191025051044_AddExpenses")]
    partial class AddExpenses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Expense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Category");

                    b.Property<DateTime>("Date");

                    b.HasKey("ID");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 25.32m,
                            Category = "Entertainment",
                            Date = new DateTime(2019, 10, 25, 0, 10, 44, 400, DateTimeKind.Local).AddTicks(9969)
                        },
                        new
                        {
                            ID = 2,
                            Amount = 78.65m,
                            Category = "Food",
                            Date = new DateTime(2019, 10, 25, 0, 10, 44, 402, DateTimeKind.Local).AddTicks(2447)
                        },
                        new
                        {
                            ID = 3,
                            Amount = 152.26m,
                            Category = "Bills",
                            Date = new DateTime(2019, 10, 25, 0, 10, 44, 402, DateTimeKind.Local).AddTicks(2456)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
